### ISSUE TITLE
Field Value Not Saving in Entries

### ISSUE THREAD

**Issue by edolyne** [encryptdesigns/Craft-Column-Widths#1]
I'm running Craft 2.5 and noticed that when editing an entry and select a value from the dropdown it is not saving.  Is this an issue with v2.5, or something that could be local to my Craft install?

**Comment by hybridinteractive** [comment]
I actually haven't tested my field type with Craft 2.5. It works well with
2.3. I am hoping to update it for 2.5 soon. Thank you for using my plugin
and I'll keep you posted on what I discover.

**Comment by hybridinteractive** [comment]
I confirmed data does save in the latest version 2.5.2757.

Did you get this sorted?

On Mon, Dec 21, 2015 at 8:17 PM, Mark encryptdesigns@gmail.com wrote:

> I actually haven't tested my field type with Craft 2.5. It works well with
> 2.3. I am hoping to update it for 2.5 soon. Thank you for using my plugin
> and I'll keep you posted on what I discover.

## 

Mark Busnelli Jr
_Encrypt Designs_
303.517.0035
encryptdesigns@gmail.com
http://www.encryptdesigns.com

**Comment by edolyne** [comment]
@encryptdesigns Thanks for letting me know, I will update the project I was working on to the latest Craft version and let you know.

**Comment by hybridinteractive** [comment]
Awesome! I also made a couple minor updates. Let me know if you have any
issues updating.

**Comment by edolyne** [comment]
Sorry it took a while to circle back around to this, I found the issue.  It appears that the field has to have a slug of columnWidth for it to save the data correctly.  Once I made the change I found that everything saves correctly.

**Comment by hybridinteractive** [comment]
That's how it was designed. I might re-evaluate that for Craft 3.

On Fri, Jan 29, 2016 at 5:08 PM, Edolyne Long notifications@github.com
wrote:

> Sorry it took a while to circle back around to this, I found the issue. It
> appears that the field has to have a slug of columnWidth for it to save the
> data correctly. Once I made the change I found that everything saves
> correctly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/encryptdesigns/Craft-Column-Widths/issues/1#issuecomment-177026911
> .

## 

Mark Busnelli Jr
_Encrypt Designs_
303.517.0035
encryptdesigns@gmail.com
http://www.encryptdesigns.com

**Comment by edolyne** [comment]
My apologies, I wasn't aware that the field needed to be named that.
